### ISSUE TITLE
No module named 'bse'

### ISSUE THREAD

**Issue by SimonStevenson** [astroJeff/dart_board#1]
Hi,

Very nice work on dart_board! I was hoping to try running the code myself.

I was following the dart_board installation guide here:
http://dart-board.readthedocs.io/en/latest/guide/install.html#

And got dart_board and pybse to install ok but when I run the example I get:

```

import numpy as np
import dart_board
import pybse

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c9163f41cdc1> in <module>()
      1 import numpy as np
      2 import dart_board
----> 3 import pybse
      4 
      5 # Set up the sampler

~/github/dart_board/pyBSE/pybse/__init__.py in <module>()
      1 
      2 
----> 3 from .bse_wrapper import *

~/github/dart_board/pyBSE/pybse/bse_wrapper.py in <module>()
      2 import sys
      3 sys.path.append("../")
----> 4 import bse
      5 import os
      6 

ModuleNotFoundError: No module named 'bse'

```

Which makes me think I have missed a step. 

Any advice would be greatly appreciated!

Thanks,
Simon

**Comment by astroJeff** [comment]
Can you check that there is a file called `bse.so` or `bse.cpython[...].so` in `dart_board/pyBSE`? If missing, the bse install failed. If it exists, try running `python test_pybse.py` and post the results.

**Comment by SimonStevenson** [comment]
Hi Jeff, 

Thanks for getting back to me.

There is no bse.so or bse.cpython .

This is the output when installing pyBSE

```
C02SD586GY25:pyBSE spstevenson$ pip install -e .
Obtaining file:///Users/spstevenson/github/dart_board/pyBSE
Installing collected packages: pybse
  Found existing installation: pybse 0.0.2
    Uninstalling pybse-0.0.2:
      Successfully uninstalled pybse-0.0.2
  Running setup.py develop for pybse
Successfully installed pybse
```
and pyBSE shows up in ```pip list```.

Obviously, python test_pybse.py fails with my original error:

```
python test_pybse.py
Traceback (most recent call last):
  File "test_pybse.py", line 1, in <module>
    import pybse
  File "/Users/spstevenson/github/dart_board/pyBSE/pybse/__init__.py", line 3, in <module>
    from .bse_wrapper import *
  File "/Users/spstevenson/github/dart_board/pyBSE/pybse/bse_wrapper.py", line 4, in <module>
    import bse
ModuleNotFoundError: No module named 'bse'
```

**Comment by astroJeff** [comment]
Simon,

For dart_board to run, BSE and its python bindings need to first be installed. I describe the extra couple steps and commands (which you should be able to copy and paste into a terminal) needed to do this in the installation guide you previously linked. 

Since BSE is not my code, it (and therefore its python bindings) must be installed separately. Please let me know if you have any trouble.

-Jeff

**Comment by SimonStevenson** [comment]
Ah success!

I thought I had followed the instructions but evidently not! I ran ```make pybse``` which made ```bse.cpython-36m-darwin.so```  and then

```
python test_pybse.py
pyBSE has been successfully installed.
```

Thanks for the help! Hopefully next time I'll have a science question!
Simon
